spring:
  application:
    name: bankingapp-fundtransfer-service
  
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:postgresql://localhost:5432/bankingapp-fund-transfers-service
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8097

bankingapp:
  kafka:
    topic:
      fund-transfers: fund-transfers-status
      transaction: transactions

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
