spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankingapp-transaction-service
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: localhost:9092


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format_sql: true
  h2:
    console:
      enabled: true


server:
  port: 8092


eureka:
  client:
    service-url:
      default-zone: http://localhost:8761
    register-with-eureka: true
    fetch-registry: false


management:
  endpoints:
    web:
      exposure:
        include: '*'
