spring:
    application:
      name: bankingapp-registry-service
    cloud:
      config:
        discovery:
          enabled: true
          service-id: bankingapp-config-server

    config:
      import: "optional:configserver:"